#!/bin/bash

#####################################################################
### delete autogenerated printer.cfg backups                      ###
#####################################################################
cd /home/pi/klipper_config
rm printer-*
